name: EnvironmentManager
version: 1.0.0
main: org.yuemi.environmentmanager.plugin.BukkitPlugin
api-version: 1.21
authors: [YueMi-Development, NekoMonci12]
commands:
  envmanager:
    description: Manage environment keys
    permission: envmanager.command